### ISSUE TITLE
Vector locations offset after window resize.

### ISSUE THREAD

**Issue by johntyree** [enthought/tabs#68]
Looks like we need to react to the map resize events and rebuild our translation matrices.

On the plus side, it is apparent now that webGL is smart about not rendering things that fall offscreen :)

**Comment by kjordahl** [comment]
e.g.:

![screen shot 2015-08-25 at 1 10 49 pm](https://cloud.githubusercontent.com/assets/499079/9478184/1f774b16-4b2b-11e5-8294-461b5095f18a.png)
